name: Update subscription

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          FRIEND_SUBS: ${{ secrets.FRIEND_SUBS }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPO: ${{ secrets.REPO }}
          GITHUB_FILE: sub.txt
          GITHUB_BRANCH: main
          PREFIX: SkyWhy/CoreLink | Node
          MAX_SERVERS: 25
          TIMEOUT: 3
          PROFILE_TITLE: LTE VPN
          PROFILE_WEB_PAGE_URL: https://t.me/твой_канал
          SUPPORT_URL: https://t.me/твой_саппорт
          ANNOUNCE: Настройки-Подписки-Сортировать по пингу, проверяйте доступность серверов ⏱️ Ping Test Регулярно обновляйте подписку!
          UPDATE_INTERVAL: 1
